/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author kuldeep
 */
public class DiaQ2 extends javax.swing.JFrame {
    private ArrayList <Diagram> aList;
    private String Question, A,B,C,D,E;
   private int count;

    /**
     * Creates new form DiaQ2
     */
    public DiaQ2() {
        initComponents();
        aList = new ArrayList <>();
       Question = new String();
       A= new String();
       B= new String();
       C= new String();
       D= new String();
       E= new String();
       
       count = 0;       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dia2Q1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AD2 = new javax.swing.JTextField();
        CD2 = new javax.swing.JTextField();
        ED2 = new javax.swing.JTextField();
        BD2 = new javax.swing.JTextField();
        DD2 = new javax.swing.JTextField();
        AddBtnDia2 = new javax.swing.JButton();
        DelBtnDia2 = new javax.swing.JButton();
        SearchBtnD2 = new javax.swing.JButton();
        DisBtndia2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        D2BtnN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Q2");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Dia2.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setText("D");

        jLabel4.setText("B");

        jLabel5.setText("C");

        jLabel6.setText("A");

        jLabel7.setText("E");

        AddBtnDia2.setText("Add");
        AddBtnDia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnDia2ActionPerformed(evt);
            }
        });

        DelBtnDia2.setText("Delete");
        DelBtnDia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBtnDia2ActionPerformed(evt);
            }
        });

        SearchBtnD2.setText("Search");

        DisBtndia2.setText("Display");
        DisBtndia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisBtndia2ActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        D2BtnN.setText("Next");
        D2BtnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2BtnNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(AD2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(ED2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(CD2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BD2)
                            .addComponent(DD2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddBtnDia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DelBtnDia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchBtnD2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DisBtndia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(D2BtnN)))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Dia2Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Dia2Q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(AD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(DD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(ED2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBtnDia2)
                    .addComponent(SearchBtnD2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DelBtnDia2)
                    .addComponent(DisBtndia2)
                    .addComponent(jButton5)
                    .addComponent(D2BtnN))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
   new DiaQ().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void AddBtnDia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnDia2ActionPerformed
        // TODO add your handling code here:
       Question = Dia2Q1.getText();
       A= AD2.getText();
       B= BD2.getText();
       C= CD2.getText();
       D= DD2.getText();
       E= ED2.getText();
       
  Diagram a = new Diagram();
        a.setQuestion(Dia2Q1);
        a.setA(A);
        a.setB(B);
        a.setC(C);
        a.setD(D);
        a.setE(E);
        
        aList.add(a);
        
        //increment counter
        count++;
        
        
        
        
    }//GEN-LAST:event_AddBtnDia2ActionPerformed

    private void DisBtndia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisBtndia2ActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < aList.size();i++){
            JOptionPane.showMessageDialog(null, "Question: "+aList.get(i).getQuestion()+"\n A: "+aList.get(i).getA()+"\n B: "+aList.get(i).getB()+"\n C: "+aList.get(i).getC()+"\n D: "+aList.get(i).getD()+"\n E: "+aList.get(i).getE());
        }
            
    }//GEN-LAST:event_DisBtndia2ActionPerformed

    private void DelBtnDia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBtnDia2ActionPerformed
        // TODO add your handling code here:
        if(Dia2Q1.getText().equals("")||AD2.getText().equals("")||BD2.getText().equals("")||CD2.getText().equals("")||DD2.getText().equals("")||ED2.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You must enter name, type and weighting to delete");
        }
        else if(count ==0){
            JOptionPane.showMessageDialog(null,"Sorry, there are no items to delete at this time");
        }
        else{
           Question = Dia2Q1.getText();
            A = AD2.getText();
              B = BD2.getText();
                C = CD2.getText();
                  D = DD2.getText();
                    E = ED2.getText();
           
            
            for(int i = 0; i < aList.size();i++){
                if(aList.get(i).getQuestion().equals(Dia2Q1)&&aList.get(i).getA().equals(AD2)&&aList.get(i).getB().equals(BD2)&&aList.get(i).getC().equals(CD2)&&aList.get(i).getD().equals(DD2)&&aList.get(i).getE().equals(ED2)){
                    aList.remove(i);
                    count = count - 1;
                    JOptionPane.showMessageDialog(null,"Deleted item at index "+i);
                    break;
                }
                if(i==count-1){
                    JOptionPane.showMessageDialog(null,"Sorry, that item could not be found");
                }
            }
        }
    }//GEN-LAST:event_DelBtnDia2ActionPerformed

    private void D2BtnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2BtnNActionPerformed
        // TODO add your handling code here:
         dispose();
   new DiaQ3().setVisible(true);
    }//GEN-LAST:event_D2BtnNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaQ2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaQ2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaQ2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaQ2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiaQ2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AD2;
    private javax.swing.JButton AddBtnDia2;
    private javax.swing.JTextField BD2;
    private javax.swing.JTextField CD2;
    private javax.swing.JButton D2BtnN;
    private javax.swing.JTextField DD2;
    private javax.swing.JButton DelBtnDia2;
    private javax.swing.JTextField Dia2Q1;
    private javax.swing.JButton DisBtndia2;
    private javax.swing.JTextField ED2;
    private javax.swing.JButton SearchBtnD2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
