/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author kuldeep
 */
public class DiaQ extends javax.swing.JFrame {

    /**
     * Creates new form DiaQ
     */
      private String ans1,ans2,ans3,ans4,ans5,ans6;
   private int count;
    private ArrayList<Answer> aList;
   
    
    public DiaQ() {
        initComponents();
         aList = new ArrayList<>();
        count = 0;
        ans1 = new String();
        ans2 = new String();
        ans3 = new String();
        ans4 = new String();
        ans5 = new String();
        ans6= new String();
        DisD.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DaTf = new javax.swing.JTextField();
        DbTf = new javax.swing.JTextField();
        DcTf = new javax.swing.JTextField();
        DdTf = new javax.swing.JTextField();
        DeTf = new javax.swing.JTextField();
        DfTf = new javax.swing.JTextField();
        BackD = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SubD = new javax.swing.JButton();
        DisD = new javax.swing.JButton();
        NextBtnD1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("            Diagram Quiz");

        jLabel3.setText("B");

        jLabel4.setText("C");

        jLabel5.setText("D");

        jLabel6.setText("E");

        jLabel7.setText("F");

        jLabel8.setText("A");

        DcTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DcTfActionPerformed(evt);
            }
        });

        DeTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeTfActionPerformed(evt);
            }
        });

        BackD.setText("Back");
        BackD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackDActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Q 1. Name The following parts of the Kidney Diagaram?");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/kidney.gif"))); // NOI18N
        jLabel10.setText("jLabel10");

        SubD.setText("Submit");
        SubD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubDActionPerformed(evt);
            }
        });

        DisD.setText("Display");
        DisD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisDActionPerformed(evt);
            }
        });

        NextBtnD1.setText("Next");
        NextBtnD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnD1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DaTf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(DfTf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(DbTf, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(DcTf, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(DdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(DeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DisD)
                                        .addGap(35, 35, 35)
                                        .addComponent(SubD)
                                        .addGap(37, 37, 37)
                                        .addComponent(NextBtnD1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 16, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BackD, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel9)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DbTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DcTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DfTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackD)
                    .addComponent(SubD)
                    .addComponent(DisD)
                    .addComponent(NextBtnD1))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(429, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeTfActionPerformed

    private void DcTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DcTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DcTfActionPerformed

    private void BackDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackDActionPerformed
        // TODO add your handling code here:
        dispose();
   new QuizOption().setVisible(true);
    }//GEN-LAST:event_BackDActionPerformed

    private void DisDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisDActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i <aList.size(); i=i+1){

            JOptionPane.showMessageDialog(null,"\n A.  "+ aList.get(i).getAns1()+"   Answer = kidney"+"\n B.  "+aList.get(i).getAns2()+"  Answer = Cortex"+"\n C."+aList.get(i).getAns3()+
                "  Answer = medulla"+    "\n D.  "+aList.get(i).getAns4()+ "  Answer = renal vein"+ "\n E.  "+aList.get(i).getAns5()+ "  Answer = renal artery"+"\n F.  "+aList.get(i).getAns6()+"  Answer = ureter");
            DisD.setVisible(false);
        }
        
    }//GEN-LAST:event_DisDActionPerformed

    private void SubDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubDActionPerformed
        // TODO add your handling code here:
         int answer = 0;
         ans1 = DaTf.getText();
        ans2 = DbTf.getText();
        ans3 = DcTf.getText();
        ans4 = DdTf.getText();
        ans5 = DeTf.getText();
        ans6 = DfTf.getText();
        
        
        Answer a = new Answer();
       a.setAns1(ans1);
       a.setAns2(ans2);
       a.setAns3(ans3);
       a.setAns4(ans4);
       a.setAns5(ans5);
       a.setAns6(ans6);
     
        // add object to arrayList
        aList.add(a);
        //increase our counter
        count++;
        
        if(ans1.equals("")&&ans2.equals("")&&ans3.equals("")&&ans4.equals("")&&ans5.equals("")&&ans6.equals("")){
            JOptionPane.showMessageDialog(null,"All fields Empty");
            
        BackD.setVisible(false);
        }
        else{
        
            if(ans1.equalsIgnoreCase("kidney")){
                answer = answer+1;
            }
            if(ans2.equalsIgnoreCase("Cortex")){
                answer = answer+1;
            }
               if(ans3.equalsIgnoreCase("medulla")){
                answer = answer+1;
            } 
                if(ans4.equalsIgnoreCase("Renal vein")){
                answer = answer+1;
            } 
               if(ans5.equalsIgnoreCase("renal artery")){
                answer= answer+1;
            }  
               if(ans6.equalsIgnoreCase("ureter")){
                answer = answer+1;
            } 
            JOptionPane.showMessageDialog(null,"NUMBER OF ATTEMPT =  "+ aList.size()+ "\n YOU SCORE : "+ answer+ "/6" );
    DisD.setVisible(true);
            BackD.setVisible(true);
        }
        
    }//GEN-LAST:event_SubDActionPerformed

    private void NextBtnD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnD1ActionPerformed
        // TODO add your handling code here:
        dispose();
   new DiaQ2().setVisible(true);
        
    }//GEN-LAST:event_NextBtnD1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiaQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackD;
    private javax.swing.JTextField DaTf;
    private javax.swing.JTextField DbTf;
    private javax.swing.JTextField DcTf;
    private javax.swing.JTextField DdTf;
    private javax.swing.JTextField DeTf;
    private javax.swing.JTextField DfTf;
    private javax.swing.JButton DisD;
    private javax.swing.JButton NextBtnD1;
    private javax.swing.JButton SubD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
