/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class MotionTrueORFalse extends javax.swing.JFrame {
  private String ans1,ans2,ans3,ans4,ans5,ans6;
   private int count;
    private ArrayList<Answer> aList;
    private int ans;
    

    /**
     * Creates new form QuizMotion
     */
    public MotionTrueORFalse() {
        initComponents();
        aList = new ArrayList<>();
        count = 0;
        ans = 0;
        ans1 = new String();
        ans2 = new String();
        ans3 = new String();
        ans4 = new String();
        ans5 = new String();
        ans6 = new String();
        DisplayBTN.setVisible(false);
        
       BackBTN.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SubmitBTH = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        Q1TF = new javax.swing.JTextField();
        DisplayBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Q2TF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Q3TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Q4TF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Q5TF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Q6TF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("1. Acceleration can be Negative.YES or NO?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 76, 371, 15);

        SubmitBTH.setBackground(new java.awt.Color(255, 0, 0));
        SubmitBTH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubmitBTH.setText("SUBMIT");
        SubmitBTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBTHActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBTH);
        SubmitBTH.setBounds(400, 470, 110, 25);

        BackBTN.setBackground(new java.awt.Color(255, 0, 0));
        BackBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackBTN.setText("BACK");
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        getContentPane().add(BackBTN);
        BackBTN.setBounds(16, 474, 90, 20);
        getContentPane().add(Q1TF);
        Q1TF.setBounds(24, 109, 155, 20);

        DisplayBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DisplayBTN.setText("DISPLAY ANSWERS");
        DisplayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBTNActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayBTN);
        DisplayBTN.setBounds(162, 471, 180, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("2. Is motion a wave. True or False?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 135, 238, 19);
        getContentPane().add(Q2TF);
        Q2TF.setBounds(22, 160, 155, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("3. The rate of change in velocity is acceleration. True or False?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 186, 400, 15);
        getContentPane().add(Q3TF);
        Q3TF.setBounds(22, 212, 155, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("4.The formula for momentum is mass times velocity. True or False?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 243, 508, 15);
        getContentPane().add(Q4TF);
        Q4TF.setBounds(22, 269, 155, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("5. Acceleration is speeding up, slowing down, or changing direction. True or False?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 307, 508, 15);
        getContentPane().add(Q5TF);
        Q5TF.setBounds(20, 340, 155, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("6. Velocity is speed in a given direction. True or False?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 371, 408, 15);
        getContentPane().add(Q6TF);
        Q6TF.setBounds(18, 404, 155, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("MOTION AND FORCE TRUE / FALSE QUESTIONS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(36, 26, 464, 32);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/Background3.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 530, 510);

        jMenu1.setBackground(new java.awt.Color(255, 51, 51));
        jMenu1.setText("EXIT");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(548, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        // TODO add your handling code here:
        Motions myFrame = new Motions();
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBTNActionPerformed

    private void SubmitBTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBTHActionPerformed
        // TODO add your handling code here:
        //get text from textfields
        int answer = 0;
        ans1 = Q1TF.getText();
        ans2 = Q2TF.getText();
        ans3 = Q3TF.getText();
        ans4 = Q4TF.getText();
        ans5 = Q5TF.getText();
        ans6 = Q6TF.getText();
        
        Answer a = new Answer();
       a.setAns1(ans1);
       a.setAns2(ans2);
       a.setAns3(ans3);
       a.setAns4(ans4);
       a.setAns5(ans5);
       a.setAns6(ans6);
        // add object to arrayList
        aList.add(a);
        //increase our counter
        count++;
        
       /* MotionQ2 myFrame = new MotionQ2();
        myFrame.setVisible(true);
        this.dispose();*/
        
        if(ans1.equals("")&&ans2.equals("")&&ans3.equals("")&&ans4.equals("")&&ans5.equals("")&&ans6.equals("")){
            JOptionPane.showMessageDialog(null,"All fields Empty");
            
        BackBTN.setVisible(false);
        }
        else{       
            if(ans1.equalsIgnoreCase("yes")){
                answer = answer+1;
            }
            if(ans2.equalsIgnoreCase("true")){
                answer = answer+1;
            }
               if(ans3.equalsIgnoreCase("true")){
                answer = answer+1;
            } 
                if(ans4.equalsIgnoreCase("true")){
                answer = answer+1;
            } 
               if(ans5.equalsIgnoreCase("true")){
                answer= answer+1;
            } 
               if(ans6.equalsIgnoreCase("true")){
                answer = answer+1;
            }
            
            
            JOptionPane.showMessageDialog(null,"NUMBER OF ATTEMPT =  "+ aList.size()+ "\n YOU SCORE : "+ answer+ "/6" );
            DisplayBTN.setVisible(true);
            BackBTN.setVisible(true);
        }
    }//GEN-LAST:event_SubmitBTHActionPerformed

    private void DisplayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBTNActionPerformed
        // TODO add your handling code here:
       /* for(int i = 0; i <arr.length; i=i+1){
            if(ans.equalsIgnoreCase("yes")){
                JOptionPane.showMessageDialog(null,"\n Q1. you wrote " + arr[i].getAns()+ " and the answer is YES"+ " CORRECT ANSWER");
            }
            else{
                JOptionPane.showMessageDialog(null,"\n Q1. you wrote " + arr[i].getAns()+ " and the answer is YES"+ " WRONG ANSWER");
            }
        }*/
        for(int i = 0; i <aList.size(); i=i+1){
            
                JOptionPane.showMessageDialog(null,"\n Q1."+ aList.get(i).getAns1()+" Answer = yes"+"\n Q2."+aList.get(i).getAns2()+"Answer = True"+"\n Q3."+aList.get(i).getAns3()+
                    "Answer = True"+    "\n Q4."+aList.get(i).getAns4()+ "Answer = True"+ "\n Q5."+aList.get(i).getAns5()+ "Answer = True"+ "\n Q6."+aList.get(i).getAns6()+"Answer = True");
           DisplayBTN.setVisible(false);
        }
    }//GEN-LAST:event_DisplayBTNActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotionTrueORFalse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotionTrueORFalse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotionTrueORFalse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotionTrueORFalse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MotionTrueORFalse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton DisplayBTN;
    private javax.swing.JTextField Q1TF;
    private javax.swing.JTextField Q2TF;
    private javax.swing.JTextField Q3TF;
    private javax.swing.JTextField Q4TF;
    private javax.swing.JTextField Q5TF;
    private javax.swing.JTextField Q6TF;
    private javax.swing.JButton SubmitBTH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
