/*
 * @author 1. OLAJIRE OLUWATOBI: x13111434
 * CLASSNAME: Motions.java
 * and open the template in the editor.
 */
package project1;

/**
 *
 * @author DELL
 */
public class Motions extends javax.swing.JFrame {

    /**
     * Creates new form Motions
     */
    public Motions() {
        initComponents();
        MultiBTN.setVisible(false);
        TrueBTN.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        QuizBTN = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MotionTA = new javax.swing.JTextArea();
        MultiBTN = new javax.swing.JRadioButton();
        TrueBTN = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(379, 330, 110, 31);

        QuizBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        QuizBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/quiz.jpg"))); // NOI18N
        QuizBTN.setText("Quiz");
        QuizBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizBTNActionPerformed(evt);
            }
        });
        getContentPane().add(QuizBTN);
        QuizBTN.setBounds(210, 320, 80, 40);

        home.setBackground(new java.awt.Color(255, 102, 0));
        home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(30, 330, 110, 30);

        MotionTA.setEditable(false);
        MotionTA.setColumns(20);
        MotionTA.setRows(5);
        MotionTA.setText("Summary\n\n• Mechanics is the study of motion, forces, and energy.\n• Motion is the action of changing location or position.\n• A force is any interaction that causes a change in motion, shape, or energy.\n• A system possesses energy if it has the ability to do work.\n(Work is done when a force causes a change in the energy of a system.)\nMechanics can be divided into sub-disciplines.\n• Kinematics is the branch of mechanics that deals with motion without regard to forces or energy.\nDynamics is the branch of mechanics that deals with motion and forces together.\nStatics is the branch of mechanics that deals with forces in the absence of changes in motion or energy.\nThe work-energy theorem is the is the central principle of mechanics that relates forces and energy.\nThe conservation of energy is the central principle of science that deals with energy in all of its forms.\nKinetic energy is the term that refers to all forms of energy due to motion.\nThere are several types of motion…\nTranslational motion results in a change of location.\nOscillatory motion is repetitive and fluctuates between two locations.\nRotational motion occurs when an object spins.\nRandom motion is unpredictable in practice or theory.");
        MotionTA.setFocusable(false);
        jScrollPane1.setViewportView(MotionTA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 510, 290);

        MultiBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MultiBTN.setText("MULTIPLE CHOICE QUESTIONS");
        MultiBTN.setContentAreaFilled(false);
        MultiBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiBTNActionPerformed(evt);
            }
        });
        getContentPane().add(MultiBTN);
        MultiBTN.setBounds(10, 37, 261, 23);

        TrueBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TrueBTN.setText("TRUE OR FALSE QUESTIONS");
        TrueBTN.setContentAreaFilled(false);
        TrueBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrueBTNActionPerformed(evt);
            }
        });
        getContentPane().add(TrueBTN);
        TrueBTN.setBounds(10, 60, 238, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 390);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(114, 34, 60, 20);

        jMenu1.setText("EXIT");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(555, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        page2 myFrame = new page2();
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        page1 myFrame = new page1();
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void QuizBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizBTNActionPerformed
        // TODO add your handling code here:
        MotionTrueORFalse myFrame = new MotionTrueORFalse();
        myFrame.setVisible(true);
        this.dispose();
       /* MotionTA.setVisible(false);
        MultiBTN.setVisible(true);
        TrueBTN.setVisible(true);
        QuizBTN.setVisible(false);*/
    }//GEN-LAST:event_QuizBTNActionPerformed

    private void TrueBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrueBTNActionPerformed
        // TODO add your handling code here:
        MotionTrueORFalse myFrame = new MotionTrueORFalse();
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TrueBTNActionPerformed

    private void MultiBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiBTNActionPerformed
        // TODO add your handling code here:
        MotionMultipleChoice myFrame = new MotionMultipleChoice();
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MultiBTNActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Motions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Motions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Motions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Motions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Motions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea MotionTA;
    private javax.swing.JRadioButton MultiBTN;
    private javax.swing.JButton QuizBTN;
    private javax.swing.JRadioButton TrueBTN;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
