/*
 * @author OLAJIRE OLUWATOBI: x13111434
 * CLASSNAME: page2.java
 * and open the template in the editor.
 */
package project1;

/**
 *
 * @author DELL
 */
public class page2 extends javax.swing.JFrame {

    /**
     * Creates new form page2
     */
    public page2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        waves = new javax.swing.JButton();
        mass = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        motion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        waves.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        waves.setText("WAVES");
        waves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wavesActionPerformed(evt);
            }
        });
        getContentPane().add(waves);
        waves.setBounds(30, 150, 96, 25);

        mass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mass.setText("MASS");
        mass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                massActionPerformed(evt);
            }
        });
        getContentPane().add(mass);
        mass.setBounds(30, 200, 96, 25);

        jButton3.setBackground(new java.awt.Color(255, 102, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 220, 90, 45);

        motion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        motion.setText("MOTION AND FORCE");
        motion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motionActionPerformed(evt);
            }
        });
        getContentPane().add(motion);
        motion.setBounds(20, 100, 198, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("PICK A TOPIC");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 10, 180, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/background4.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 280);

        jMenu1.setText("EXIT");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(415, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        page1 myFrame = new page1();
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void massActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_massActionPerformed
        // TODO add your handling code here:
        Mass myFrame = new Mass();
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_massActionPerformed

    private void motionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motionActionPerformed
        // TODO add your handling code here:
        Motions myFrame = new Motions();
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_motionActionPerformed

    private void wavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wavesActionPerformed
        // TODO add your handling code here:
        Waves myFrame = new Waves();
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_wavesActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton mass;
    private javax.swing.JButton motion;
    private javax.swing.JButton waves;
    // End of variables declaration//GEN-END:variables
}
