/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

/**
 *
 * @author kuldeep
 */
public class QuizOption extends javax.swing.JFrame {

    /**
     * Creates new form QuizOption
     */
    public QuizOption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Multibtn1 = new javax.swing.JButton();
        diabtn1 = new javax.swing.JButton();
        flashbtn1 = new javax.swing.JButton();
        backbtn2 = new javax.swing.JButton();
        Lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Multibtn1.setBackground(new java.awt.Color(51, 51, 255));
        Multibtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Multibtn1.setText("Multiple Choice ");
        Multibtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Multibtn1ActionPerformed(evt);
            }
        });

        diabtn1.setBackground(new java.awt.Color(255, 0, 153));
        diabtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        diabtn1.setText("Diagram");
        diabtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diabtn1ActionPerformed(evt);
            }
        });

        flashbtn1.setBackground(new java.awt.Color(51, 204, 0));
        flashbtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        flashbtn1.setText("Flash card");
        flashbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flashbtn1ActionPerformed(evt);
            }
        });

        backbtn2.setBackground(new java.awt.Color(255, 255, 0));
        backbtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backbtn2.setText("Back");
        backbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn2ActionPerformed(evt);
            }
        });

        Lbl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lbl2.setText("Choose Quiz Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Multibtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diabtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flashbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(Lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl2)
                .addGap(34, 34, 34)
                .addComponent(Multibtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diabtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(flashbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(backbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        setSize(new java.awt.Dimension(349, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Multibtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Multibtn1ActionPerformed
        // TODO add your handling code here:
        dispose();
   new MultiQ().setVisible(true);
    }//GEN-LAST:event_Multibtn1ActionPerformed

    private void flashbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flashbtn1ActionPerformed
        // TODO add your handling code here:
        dispose();
   new FlashQ().setVisible(true);
    }//GEN-LAST:event_flashbtn1ActionPerformed

    private void diabtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diabtn1ActionPerformed
        // TODO add your handling code here:
        dispose();
   new DiaQ().setVisible(true);
    }//GEN-LAST:event_diabtn1ActionPerformed

    private void backbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn2ActionPerformed
        // TODO add your handling code here:
        dispose();
   new BioOption().setVisible(true);
    }//GEN-LAST:event_backbtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl2;
    private javax.swing.JButton Multibtn1;
    private javax.swing.JButton backbtn2;
    private javax.swing.JButton diabtn1;
    private javax.swing.JButton flashbtn1;
    // End of variables declaration//GEN-END:variables
}
