/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class WaveTrueORFalse extends javax.swing.JFrame {
   private String ans1,ans2,ans3,ans4,ans5;
   private int count;
    private ArrayList<Answer> aList;
    
    /**
     * Creates new form QuizWave
     */
    public WaveTrueORFalse() {
        initComponents();
        aList = new ArrayList<>();
        count = 0;
        ans1 = new String();
        ans2 = new String();
        ans3 = new String();
        ans4 = new String();
        ans5 = new String();
        DisplayBTN.setVisible(false);
        BackBTN.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubmitBTN = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        DisplayBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Q1TF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Q2TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Q3TF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Q4TF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Q5TF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        SubmitBTN.setBackground(new java.awt.Color(255, 0, 0));
        SubmitBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SubmitBTN.setText("SUBMIT");
        SubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBTN);
        SubmitBTN.setBounds(520, 370, 99, 25);

        BackBTN.setBackground(new java.awt.Color(255, 0, 0));
        BackBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackBTN.setText("BACK");
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        getContentPane().add(BackBTN);
        BackBTN.setBounds(26, 375, 110, 25);

        DisplayBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DisplayBTN.setText("DISPLAY ANSWERS");
        DisplayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayBTNActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayBTN);
        DisplayBTN.setBounds(230, 370, 190, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("WAVE TRUE / FALSE QUESTIONS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(128, 7, 319, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("1. Constructive interference of waves occurs when two crests meet.True or False?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(26, 59, 591, 15);
        getContentPane().add(Q1TF);
        Q1TF.setBounds(36, 80, 100, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("2.The SI unit for frequency is hertz. True or False?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(26, 111, 339, 15);
        getContentPane().add(Q2TF);
        Q2TF.setBounds(36, 137, 100, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("3. The number of waves generated per second by a source is called the frequency of the source.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(26, 168, 591, 15);
        getContentPane().add(Q3TF);
        Q3TF.setBounds(36, 189, 100, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("4. A vibrating object is necessary for the production of sound.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(26, 220, 505, 15);
        getContentPane().add(Q4TF);
        Q4TF.setBounds(36, 241, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("5. Doubling the frequency of a wave source (without altering the medium) doubles the speed of the waves.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(26, 272, 666, 15);
        getContentPane().add(Q5TF);
        Q5TF.setBounds(36, 293, 100, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/background4.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 710, 410);

        jMenu1.setText("EXIT");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(726, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        // TODO add your handling code here:
       Waves myFrame = new Waves();
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBTNActionPerformed

    private void DisplayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayBTNActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i <aList.size(); i=i+1){
            
                JOptionPane.showMessageDialog(null,"\n Q1.  "+ aList.get(i).getAns1()+"   Answer = true"+"\n Q2.  "+aList.get(i).getAns2()+"  Answer = True"+"\n Q3."+aList.get(i).getAns3()+
                    "  Answer = True"+    "\n Q4.  "+aList.get(i).getAns4()+ "  Answer = True"+ "\n Q5.  "+aList.get(i).getAns5()+ "  Answer = false");
           DisplayBTN.setVisible(false);
        }
        
    }//GEN-LAST:event_DisplayBTNActionPerformed

    private void SubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBTNActionPerformed
        // TODO add your handling code here:
        int answer = 0;
         ans1 = Q1TF.getText();
        ans2 = Q2TF.getText();
        ans3 = Q3TF.getText();
        ans4 = Q4TF.getText();
        ans5 = Q5TF.getText();
        
        
        Answer a = new Answer();
       a.setAns1(ans1);
       a.setAns2(ans2);
       a.setAns3(ans3);
       a.setAns4(ans4);
       a.setAns5(ans5);
     
        // add object to arrayList
        aList.add(a);
        //increase our counter
        count++;
        
        if(ans1.equals("")&&ans2.equals("")&&ans3.equals("")&&ans4.equals("")&&ans5.equals("")){
            JOptionPane.showMessageDialog(null,"All fields Empty");
            
        BackBTN.setVisible(false);
        }
        else{
        
            if(ans1.equalsIgnoreCase("true")){
                answer = answer+1;
            }
            if(ans2.equalsIgnoreCase("true")){
                answer = answer+1;
            }
               if(ans3.equalsIgnoreCase("true")){
                answer = answer+1;
            } 
                if(ans4.equalsIgnoreCase("true")){
                answer = answer+1;
            } 
               if(ans5.equalsIgnoreCase("false")){
                answer= answer+1;
            }             
            JOptionPane.showMessageDialog(null,"NUMBER OF ATTEMPT =  "+ aList.size()+ "\n YOU SCORE : "+ answer+ "/5" );
    DisplayBTN.setVisible(true);
            BackBTN.setVisible(true);
        }
    }//GEN-LAST:event_SubmitBTNActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaveTrueORFalse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaveTrueORFalse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaveTrueORFalse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaveTrueORFalse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WaveTrueORFalse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton DisplayBTN;
    private javax.swing.JTextField Q1TF;
    private javax.swing.JTextField Q2TF;
    private javax.swing.JTextField Q3TF;
    private javax.swing.JTextField Q4TF;
    private javax.swing.JTextField Q5TF;
    private javax.swing.JButton SubmitBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
